remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: UNT Machine learning in Chemistry and Material Science Seminar
description: 

show_downloads: false
github.is_project_page: false
